name: ci
job_dirs:
  - ".buildkite/test_areas"
  - ".buildkite/image_build"
run_all_patterns:
  - ".*"
run_all_exclude_patterns:
  - ".*"
registries: public.ecr.aws/q9t5s3a7
repositories:
  main: "vllm-ci-postmerge-repo"
  premerge: "vllm-ci-test-repo"
