# test_config.yaml
stages:
  - name: test_gsm8k_small_models
    steps:
      - name: gsm8k_small_g3_tp1
        flavor: g3
        command: cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-small.txt -t 1
      - name: gsm8k_small_g3_tp2
        flavor: g3.s
        command: cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-small.txt -t 2
      - name: gsm8k_small_g2_tp1
        flavor: g2
        command: cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-small.txt -t 1
      - name: gsm8k_small_g2_tp2
        flavor: g2.s
        command: cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-small.txt -t 2
  - name: test_gsm8k_large_models
    steps:
      - name: gsm8k_large_g3_tp2
        flavor: g3.s
        command: cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-large.txt -t 2
      - name: gsm8k_large_g2_tp4
        flavor: g2.m
        command: cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-large.txt -t 4
  - name: test_gsm8k_fp8
    steps:
      - name: gsm8k_small_g3_tp1_fp8
        flavor: g3
        command: cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-fp8.txt -t 1
      - name: gsm8k_small_g3_tp2_fp8
        flavor: g3.s
        command: cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-fp8.txt -t 2
  - name: test_gsm8k_mss
    steps:
      - name: gsm8k_small_g3_tp1_mss
        flavor: g3
        command: cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-mss.txt -t 1
      - name: gsm8k_small_g2_tp1_mss
        flavor: g2
        command: cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-mss.txt -t 1
      - name: gsm8k_small_g3_tp2_mss
        flavor: g3.s
        command: cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-mss.txt -t 2
      - name: gsm8k_small_g2_tp2_mss
        flavor: g2.s
        command: cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-mss.txt -t 2
      - name: gsm8k_small_g2_tp1_spec_decode
        flavor: g2
        command: cd .jenkins/lm-eval-harness && bash run-tests.sh -c configs/models-mss.txt -t 1
  - name: test_gsm8k_spec_decode
    steps:
      - name: gsm8k_small_g2_tp1_mlp_spec_decode
        flavor: g2
        command: TORCH_COMPILE_DISABLE=true VLLM_CONTIGUOUS_PA=false VLLM_SKIP_WARMUP=True pytest -v tests/spec_decode/e2e/test_mlp_correctness.py::test_mlp_e2e_greedy_correctness 
      - name: gsm8k_small_g2_tp1_medusa_spec_decode
        flavor: g2
        command: TORCH_COMPILE_DISABLE=true VLLM_CONTIGUOUS_PA=false VLLM_SKIP_WARMUP=True pytest -v tests/spec_decode/e2e/test_medusa_correctness.py::test_medusa_e2e_greedy_correctness
      - name: gsm8k_small_g2_tp1_eagle_spec_decode
        flavor: g2
        command: TORCH_COMPILE_DISABLE=true VLLM_CONTIGUOUS_PA=false VLLM_SKIP_WARMUP=True pytest -v tests/spec_decode/e2e/test_eagle_correctness.py::test_eagle_e2e_greedy_correctness
