name: generate whl
run-name: ${{ github.actor }} generating whl on branch '${{ github.ref }}'
on:
  workflow_dispatch:
    inputs:
        gitref:
            description: 'git commit hash or branch name'
            type: string
            required: true

jobs:

  AWS-AVX2-32G-A10G-24G:
    strategy:
      matrix:
            python: [3.8.17, 3.9.17, 3.10.12, 3.11.4]
    uses: ./.github/workflows/build-whl.yml
    with:
        build_label: aws-avx2-192G-4-a10g-96G
        timeout: 30
        gitref: ${{ inputs.gitref }}
        Gi_per_thread: 4
        python: ${{ matrix.python }}
    secrets: inherit
