name: nm Nightly
run-name: ${{ github.actor }} triggered nightly on ${{ github.ref }}
on:
    schedule:
      # * is a special character in YAML so you have to quote this string
      - cron: '0 1 * * 1-6'  # nightly run (Mon-Sat)

    workflow_dispatch:
        inputs:
            push_benchmark_results_to_gh_pages:
                description: "When set to true, the workflow pushes all benchmarking results to gh-pages UI "
                type: choice
                options:
                    - 'true'
                    - 'false'
                default: 'false'

jobs:

    PYTHON-3-8:
        uses: ./.github/workflows/nm-build-test.yml
        with:
            wf_category: NIGHTLY
            python: 3.8.17
            gitref: ${{ github.ref }}

            test_label_solo: gcp-k8s-l4-solo
            test_label_multi: ignore
            test_timeout: 480
            test_skip_list: neuralmagic/tests/skip-for-nightly.txt

            benchmark_label: gcp-k8s-l4-solo
            benchmark_config_list_file: ./.github/data/nm_benchmark_remote_push_configs_list.txt
            benchmark_timeout: 720
            push_benchmark_results_to_gh_pages: "${{ github.event_name == 'schedule' || inputs.push_benchmark_results_to_gh_pages }}"
        secrets: inherit

    PYTHON-3-9:
        uses: ./.github/workflows/nm-build-test.yml
        with:
            wf_category: NIGHTLY
            python: 3.9.17
            gitref: ${{ github.ref }}

            test_label_solo: gcp-k8s-l4-solo
            test_label_multi: ignore
            test_timeout: 480
            test_skip_list: neuralmagic/tests/skip-for-nightly.txt

            benchmark_label: gcp-k8s-l4-solo
            benchmark_config_list_file: ./.github/data/nm_benchmark_remote_push_configs_list.txt
            benchmark_timeout: 720
            push_benchmark_results_to_gh_pages: "${{ github.event_name == 'schedule' || inputs.push_benchmark_results_to_gh_pages }}"
        secrets: inherit

    PYTHON-3-10:
        uses: ./.github/workflows/nm-build-test.yml
        with:
            wf_category: NIGHTLY
            python: 3.10.12
            gitref: ${{ github.ref }}

            test_label_solo: aws-avx2-32G-a10g-24G
            test_label_multi: ignore
            test_timeout: 480
            test_skip_list: neuralmagic/tests/skip-for-nightly.txt

            benchmark_label: gcp-k8s-l4-solo
            benchmark_config_list_file: ./.github/data/nm_benchmark_remote_push_configs_list.txt
            benchmark_timeout: 720
            push_benchmark_results_to_gh_pages: "${{ github.event_name == 'schedule' || inputs.push_benchmark_results_to_gh_pages }}"
        secrets: inherit

    PYTHON-3-11:
        uses: ./.github/workflows/nm-build-test.yml
        with:
            wf_category: NIGHTLY
            python: 3.11.4
            gitref: ${{ github.ref }}

            test_label_solo: gcp-k8s-l4-solo
            test_label_multi: ignore
            test_timeout: 480
            test_skip_list: neuralmagic/tests/skip-for-nightly.txt

            benchmark_label: gcp-k8s-l4-solo
            benchmark_config_list_file: ./.github/data/nm_benchmark_remote_push_configs_list.txt
            benchmark_timeout: 720
            push_benchmark_results_to_gh_pages: "${{ github.event_name == 'schedule' || inputs.push_benchmark_results_to_gh_pages }}"
        secrets: inherit
