name: nm test
on:
  # makes workflow reusable
  workflow_call:
    inputs:
      test_label:
        description: "requested runner label (specifies instance)"
        type: string
        required: true
      timeout:
        description: "time limit for run in minutes "
        type: string
        required: true
      gitref:
        description: "git commit hash or branch name"
        type: string
        required: true
      python:
        description: "python version, e.g. 3.10.12"
        type: string
        required: true
      whl:
        description: "whl to test (variable appears late binding so unusable outside 'download artifact')"
        type: string
        required: true
      test_skip_list:
        description: 'file containing tests to skip'
        type: string
        required: true

  # makes workflow manually callable
  workflow_dispatch:
    inputs:
      test_label:
        description: "requested runner label (specifies instance)"
        type: string
        required: true
      timeout:
        description: "time limit for run in minutes "
        type: string
        required: true
      gitref:
        description: "git commit hash or branch name"
        type: string
        required: true
      python:
        description: "python version, e.g. 3.10.12"
        type: string
        required: true
      whl:
        description: "whl to test (variable appears late binding so unusable outside 'download artifact')"
        type: string
        required: true
      test_skip_list:
        description: 'file containing tests to skip'
        type: string
        required: true

jobs:

    TEST:

        runs-on: ${{ inputs.test_label }}
        timeout-minutes: ${{ fromJson(inputs.timeout) }}

        steps:

            - name: set python
              id: set_python
              uses: actions/setup-python@v5
              with:
                python-version: ${{ inputs.python }}

            - name: install automation components
              run: |
                sudo apt-get update --fix-missing
                sudo apt-get install -y git-all
                sudo apt-get install -y curl

            - name: checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                ref: ${{ inputs.gitref }}
                submodules: recursive

            - name: setenv
              id: setenv
              uses: ./.github/actions/nm-set-env/
              with:
                hf_token: ${{ secrets.NM_HF_TOKEN }}
                Gi_per_thread: 1
                nvcc_threads: 0

            - name: install testmo
              uses: ./.github/actions/nm-install-testmo/

            - name: create testmo run
              id: create_testmo_run
              uses: ./.github/actions/nm-testmo-run-create/
              if: success() || failure()
              with:
                testmo_url: https://neuralmagic.testmo.net
                testmo_token: ${{ secrets.TESTMO_TEST_TOKEN }}
                source: 'build-test'

            - name: verify python
              id: verify_python
              uses: ./.github/actions/nm-verify-python/

            - name: hf cache
              id: hf_cache
              uses: ./.github/actions/nm-hf-cache/
              with:
                fs_cache: ${{ secrets.HF_FS_CACHE }}

            - name: download whl
              id: download
              uses: actions/download-artifact@v4
              with:
                name: ${{ inputs.whl }}
                path: ${{ inputs.whl }}

            - name: install whl
              uses: ./.github/actions/nm-install-whl/
              with:
                python: ${{ inputs.python }}
                venv:

            - name: run buildkite script
              run: |
                cd tests && sudo bash ../.buildkite/download-images.sh

            - name: run tests
              id: test
              uses: ./.github/actions/nm-test-whl/
              with:
                test_skip_list: ${{ inputs.test_skip_list }}
                test_directory: tests
                test_results: test-results

            - name: upload code coverage html
              uses: actions/upload-artifact@v4
              if: success() || failure()
              with:
                name: cc-vllm-html-${{ inputs.test_label }}-${{ inputs.python }}
                path: cc-vllm-html
                retention-days: 15

            - name: report test results
              id: report_test
              uses: ./.github/actions/nm-testmo-run-submit-thread/
              if: success() || failure()
              with:
                testmo_url: https://neuralmagic.testmo.net
                testmo_token: ${{ secrets.TESTMO_TEST_TOKEN }}
                testmo_run_id: ${{ steps.create_testmo_run.outputs.id }}
                results: test-results
                step_status: ${{ steps.test.outputs.status }}

            - name: summary
              uses: ./.github/actions/nm-summary-test/
              if: success() || failure()
              with:
                test_label: ${{ inputs.test_label }}
                gitref: ${{ inputs.gitref }}
                testmo_run_url: https://neuralmagic.testmo.net/automation/runs/view/${{ steps.create_testmo_run.outputs.id }}
                python: ${{ steps.verify_python.outputs.version }}
                whl: ${{ steps.test.outputs.whl }}
                magic_wand: ${{ steps.test.outputs.magic_wand }}
                test_status: ${{ steps.test.outputs.status }}

            - name: complete testmo run
              uses: ./.github/actions/nm-testmo-run-complete/
              if: success() || failure()
              with:
                testmo_url: https://neuralmagic.testmo.net
                testmo_token: ${{ secrets.TESTMO_TEST_TOKEN }}
                testmo_run_id: ${{ steps.create_testmo_run.outputs.id }}
