name: Publish Helm chart on Github Registry

# Configures this workflow to run every time a change is pushed to the branch called `main`.
on:
  push:
    paths:
      - 'examples/online_serving/chart-helm/**'
env:
  CHART_NAME: chart-vllm

jobs:
  package-and-publish-chart-helm:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      # 
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
        with:
          version: v3.14.4

      - name: helm login
        run:  echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u $ --password-stdin

      - name: get helm chart version
        run:  echo "CHART_TAG=$(helm show chart examples/online_serving/chart-helm | awk '/version/ {print $2}')" >> "$GITHUB_ENV"

      - name: helm package
        run:  helm package examples/online_serving/chart-helm --version ${{ env.CHART_TAG }}

      - name: helm push
        run:  helm push /home/runner/work/vllm/vllm/${{ env.CHART_NAME }}-${{ env.CHART_TAG }}.tgz oci://ghcr.io/${{ github.repository_owner }}