name: remote push
run-name: ${{ github.actor }} verifying branch '${{ github.ref }}'
on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:

    BUILD-TEST-3-8:
        uses: ./.github/workflows/build-test.yml
        with:
            python: 3.8.17
            gitref: ${{ github.ref }}

            test_label_solo: aws-avx2-32G-a10g-24G
            test_label_multi: ignore
            test_timeout: 480
            test_skip_list: neuralmagic/tests/skip-for-remote-push.txt

            benchmark_label: aws-avx2-32G-a10g-24G
            benchmark_config_list_file: ./.github/data/nm_benchmark_remote_push_configs_list.txt
            benchmark_timeout: 480
        secrets: inherit

    BUILD-TEST-3-10:
        uses: ./.github/workflows/build-test.yml
        with:
            python: 3.10.12
            gitref: ${{ github.ref }}

            test_label_solo: aws-avx2-32G-a10g-24G
            test_label_multi: ignore
            test_timeout: 480
            test_skip_list: neuralmagic/tests/skip-for-remote-push.txt

            benchmark_label: aws-avx2-32G-a10g-24G
            benchmark_config_list_file: ./.github/data/nm_benchmark_remote_push_configs_list.txt
            benchmark_timeout: 480
        secrets: inherit
