name: remote push
run-name: ${{ github.actor }} verifying branch '${{ github.ref }}'
on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:

    # TODO: expand python matrix later, once CI system has matured.

    # multi-gpu
    AWS-AVX2-192G-4-A10G-96G:
        strategy:
            matrix:
                python: [3.10.12]
        uses: ./.github/workflows/build-test.yml
        with:
            label: aws-avx2-192G-4-a10g-96G
            timeout: 180
            gitref: '${{ github.ref }}'
            Gi_per_thread: 4
            python: ${{ matrix.python }}
        secrets: inherit
